version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-config:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build: api
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    restart: always

volumes:
  rabbitmq-data:
  rabbitmq-config:
